apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-cms-root
  namespace: argocd
spec:
  project: enterprise-cms
  source:
    repoURL: https://github.com/alimulfazalnabil/Power-Grid-Company-of-Bangladesh-PGCB-Diploma-Engineers-Website
    targetRevision: alimul-fazal-nabil/set-up-the-development-environment-fxHTwH
    path: kubernetes/argocd
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true