apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: enterprise-cms-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: enterprise-cms-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
