{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app.kubernetes.io/name: enterprise-cms-web
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: enterprise-cms-web
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: enterprise-cms-web
        app.kubernetes.io/instance: {{ .Release.Name }}
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ .Values.web.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.security.podSecurityContext | nindent 8 }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: {{ printf "%s/%s:%s" .Values.global.imageRegistry .Values.web.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.security.containerSecurityContext | nindent 12 }}
          ports:
            - containerPort: {{ .Values.web.service.port }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          livenessProbe:
            httpGet:
              path: {{ .Values.web.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.web.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.web.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.web.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.probes.readiness.periodSeconds }}
          startupProbe:
            httpGet:
              path: {{ .Values.web.probes.startup.path }}
              port: http
            failureThreshold: {{ .Values.web.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.web.probes.startup.periodSeconds }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
{{- end }}
