{{- if .Values.localDependencies.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: enterprise-cms-local-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: enterprise-cms-local-redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: enterprise-cms-local-redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.localDependencies.redis.image }}
          ports:
            - containerPort: 6379
{{- end }}
