{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-web-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: enterprise-cms-web
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {{ toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 12 }}
      ports:
        - protocol: TCP
          port: {{ .Values.web.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-web-to-api
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: enterprise-cms-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: enterprise-cms-web
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: {{ .Values.api.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-api-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: enterprise-cms-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Egress
  egress:
    - to:
        {{- range .Values.networkPolicy.postgresCidrs }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 5432
    - to:
        {{- range .Values.networkPolicy.redisCidrs }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 6380
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- if .Values.worker.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-worker-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: enterprise-cms-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Egress
  egress:
    - to:
        {{- range .Values.networkPolicy.postgresCidrs }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 5432
    - to:
        {{- range .Values.networkPolicy.redisCidrs }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 6380
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}
{{- end }}
