apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.web.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: enterprise-cms-web
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    {{- if .Values.web.serviceAccount.clientId }}
    azure.workload.identity/client-id: {{ .Values.web.serviceAccount.clientId | quote }}
    {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.api.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: enterprise-cms-api
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    {{- if .Values.api.serviceAccount.clientId }}
    azure.workload.identity/client-id: {{ .Values.api.serviceAccount.clientId | quote }}
    {{- end }}
{{- if .Values.worker.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.worker.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: enterprise-cms-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    {{- if .Values.worker.serviceAccount.clientId }}
    azure.workload.identity/client-id: {{ .Values.worker.serviceAccount.clientId | quote }}
    {{- end }}
{{- end }}
{{- if .Values.monitoring.otelCollector.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.monitoring.otelCollector.serviceAccountName }}
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
